kitchen/urls.py
from django.urls import path

from .views import (
    index,
    DishListView,
    DishDetailView,
    DishCreateView,
    toggle_assign_to_dish,
    DishUpdateView,
    DishDeleteView,
    CookListView,
    CookDetailView,
    CookCreateView,
    CookExperienceUpdateView,
    CookDeleteView,
    DishTypeListView,
    DishTypeCreateView,
    DishTypeUpdateView,
    DishTypeDeleteView,
    IngredientListView,
    IngredientCreateView,
    IngredientUpdateView,
    IngredientDeleteView,
    remove_add_cook_to_dish,
    no_page
)


urlpatterns = [
    path("", index, name="index"),
    path("dishes/", DishListView.as_view(), name="dish-list"),
    path("dishes/<int:pk>/", DishDetailView.as_view(), name="dish-detail"),
    path("dishes/create", DishCreateView.as_view(), name="dish-create"),
    path(
        "dishes/<int:pk>/toggle-assign/",
        toggle_assign_to_dish,
        name="toggle-dish-assign"
    ),
    path("dishes/<int:pk>/update/", DishUpdateView.as_view(), name="dish-update"),
    path("dishes/<int:pk>/delete/", DishDeleteView.as_view(), name="dish-delete"),
    path("cooks/", CookListView.as_view(), name="cook-list"),
    path("cooks/<int:pk>/", CookDetailView.as_view(), name="cook-detail"),
    path("cooks/<int:pk>/update/",
         CookExperienceUpdateView.as_view(), name="cook-update"),
    path("cooks/<int:pk>/delete/", CookDeleteView.as_view(), name="cook-delete"),
    path("cooks/create", CookCreateView.as_view(), name="cook-create"),
    path(
        "dishtypes/",
        DishTypeListView.as_view(),
        name="dishtype-list",
    ),
    path(
        "dishtypes/create/",
        DishTypeCreateView.as_view(),
        name="dishtype-create",
    ),
    path(
        "dishtypes/<int:pk>/update/",
        DishTypeUpdateView.as_view(),
        name="dishtype-update",
    ),
    path(
        "dishtypes/<int:pk>/delete/",
        DishTypeDeleteView.as_view(),
        name="dishtype-delete",
    ),
    path(
        "ingredients/",
        IngredientListView.as_view(),
        name="ingredient-list",
    ),
    path(
        "ingredients/create/",
        IngredientCreateView.as_view(),
        name="ingredient-create",
    ),
    path(
        "ingredients/<int:pk>/update/",
        IngredientUpdateView.as_view(),
        name="ingredient-update",
    ),
    path(
        "ingredients/<int:pk>/delete/",
        IngredientDeleteView.as_view(),
        name="ingredient-delete",
    ),
    path("dishes/<int:pk>/remove_add_cook_to_dish/",
        remove_add_cook_to_dish, name="remove-add-cook-to-dish"
    ),
    path("404/", no_page, name="no-page")
]



app_name = "kitchen"

kitchen_service/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("kitchen.urls", namespace="kitchen")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

kitchen/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.urls import reverse
from django.db.models import UniqueConstraint
from django.conf import settings


class DishType(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ["id"]

    def __str__(self) -> str:
        return self.name


class Cook(AbstractUser):
    years_of_experience = models.IntegerField(null=True)

    class Meta:
        verbose_name = "cook"
        verbose_name_plural = "cooks"
        ordering = ["-years_of_experience"]

    def __str__(self) -> str:
        return f"{self.username} ({self.first_name} {self.last_name})"

    def get_absolute_url(self):
        return reverse("kitchen:dish-detail", kwargs={"pk": self.pk})


class Ingredient(models.Model):
    name = models.CharField(max_length=255, null=False)
    amount = models.IntegerField(null=False)
    unit = models.CharField(max_length=255, null=False)

    class Meta:
        ordering = ["name"]
        constraints = [
            UniqueConstraint(
                fields=["name", "amount", "unit"],
                name="uniq_name_amount_unit"
            )
        ]

    def __str__(self) -> str:
        return f"{self.name} -> {self.amount} ({self.unit})"


class Dish(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, max_length=255)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    dish_type = models.ForeignKey(DishType, on_delete=models.CASCADE)
    cooks = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name="dishes"
    )
    ingredients = models.ManyToManyField(
        Ingredient,
        related_name="dishes"
    )

    class Meta:
        ordering = ["id"]

    def __str__(self) -> str:
        return f"{self.name} price: {self.price}"

kitchen/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError

from kitchen.models import Dish, Cook, Ingredient, DishType


class DishForm(forms.ModelForm):
    cooks = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )
    ingredients = forms.ModelMultipleChoiceField(
        queryset=Ingredient.objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )
    dish_type = forms.ModelChoiceField(queryset=DishType.objects.all(
    ), widget=forms.Select(attrs={'class': "info_header-text blur shadow-blur"}))

    class Meta:
        model = Dish
        fields = ["name", "price", "description",
                  "dish_type", "cooks", "ingredients"]
        widgets = {
            "name": forms.TextInput(attrs={
                "class": "info_header-text blur shadow-blur",
                "placeholder": "name",
                "required": True
            }),
            "price": forms.TextInput(attrs={
                "class": "info_header-text blur shadow-blur",
                "placeholder": "price $"
            }),
            "description": forms.Textarea(attrs={
                "class": "info_desc blur shadow-blur",
                "placeholder": "Enter description here..."
            }),
        }


class DishSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={"placeholder": "Search by name..."}
        )
    )


class CookCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = Cook
        fields = UserCreationForm.Meta.fields + (
            "years_of_experience",
            "first_name",
            "last_name",
        )

    def clean_license_number(self):  # this logic is optional, but possible
        return validate_years_of_experience(self.cleaned_data["years_of_experience"])


class CookExperienceUpdateForm(forms.ModelForm):
    class Meta:
        model = Cook
        fields = ["years_of_experience"]

    def clean_license_number(self):
        return validate_years_of_experience(self.cleaned_data["years_of_experience"])


def validate_years_of_experience(years_of_experience,):
    if years_of_experience < 0:
        raise ValidationError("Experience years can`t be negative")
    elif not years_of_experience.is_integer():
        raise ValidationError("It should be integer value")

    return years_of_experience


class CookUsernameSearchForm(forms.Form):
    username = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by username..."})
    )


class DishTypeSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by name..."})
    )


class IngredientSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by name..."})
    )

kitchen/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import DishType, Cook, Dish, Ingredient
from .forms import (
    DishSearchForm,
    DishForm,
    CookUsernameSearchForm,
    CookCreationForm,
    CookExperienceUpdateForm,
    DishTypeSearchForm,
    IngredientSearchForm
)


@login_required
def index(request):
    """View function for the home page of the site."""
    num_cooks = Cook.objects.count()
    num_dishes = Dish.objects.count()
    num_dish_types = DishType.objects.count()

    num_visits = request.session.get("num_visits", 0)
    request.session["num_visits"] = num_visits + 1

    context = {
        "num_dishes": num_dishes,
        "num_dish_types": num_dish_types,
        "num_cooks": num_cooks,
        "num_visits": num_visits + 1,
    }

    return render(request, "kitchen/index.html", context=context)


@login_required
def no_page(request):
    return render(request, "kitchen/no_page.html")


class DishListView(LoginRequiredMixin, generic.ListView):
    model = Dish
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)

        name = self.request.GET.get("name", "")
        context["search_form"] = DishSearchForm(
            initial={"name": name}
        )

        return context

    def get_queryset(self):
        queryset = Dish.objects.select_related("dish_type")

        form = DishSearchForm(self.request.GET)

        if form.is_valid():
            return queryset.filter(
                name__icontains=form.cleaned_data["name"]
            )

        return queryset


class DishCreateView(LoginRequiredMixin, generic.CreateView):
    model = Dish
    form_class = DishForm
    success_url = reverse_lazy("kitchen:dish-list")


class DishDetailView(LoginRequiredMixin, generic.DetailView):
    model = Dish


class DishUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Dish
    form_class = DishForm
    success_url = reverse_lazy("kitchen:dish-list")


class DishDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Dish
    success_url = reverse_lazy("kitchen:dish-list")


class CookListView(LoginRequiredMixin, generic.ListView):
    model = Cook
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)

        username = self.request.GET.get("username", "")
        context["search_form"] = CookUsernameSearchForm(
            initial={"username": username}
        )

        return context

    def get_queryset(self):
        username = self.request.GET.get("username")

        if username:
            return super().get_queryset().filter(username__icontains=username)

        return super().get_queryset()


class CookDetailView(LoginRequiredMixin, generic.DetailView):
    model = Cook
    queryset = Cook.objects.prefetch_related("dishes__dish_type")


class CookCreateView(LoginRequiredMixin, generic.CreateView):
    model = Cook
    form_class = CookCreationForm
    success_url = reverse_lazy("kitchen:cook-list")


class CookExperienceUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Cook
    form_class = CookExperienceUpdateForm
    success_url = reverse_lazy("kitchen:cook-list")


class CookDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Cook
    success_url = reverse_lazy("")


@login_required
def toggle_assign_to_dish(request, pk):
    cook = Cook.objects.get(id=request.user.id)
    if (
        Dish.objects.get(id=pk) in cook.dishes.all()
    ):  # probably could check if car exists
        cook.dishes.remove(pk)
    else:
        cook.dishes.add(pk)
    return HttpResponseRedirect(reverse_lazy("kitchen:dish-detail", args=[pk]))


class DishTypeListView(LoginRequiredMixin, generic.ListView):
    model = DishType
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)

        name = self.request.GET.get("name", "")
        context["search_form"] = DishTypeSearchForm(
            initial={"name": name}
        )

        return context

    def get_queryset(self):
        name = self.request.GET.get("name")

        if name:
            return super().get_queryset().filter(name__icontains=name)

        return super().get_queryset()


class DishTypeCreateView(LoginRequiredMixin, generic.CreateView):
    model = DishType
    fields = "__all__"
    success_url = reverse_lazy("kitchen:dishtype-list")


class DishTypeUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = DishType
    fields = "__all__"
    success_url = reverse_lazy("kitchen:dishtype-list")


class DishTypeDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = DishType
    success_url = reverse_lazy("kitchen:dishtype-list")
    

class IngredientListView(LoginRequiredMixin, generic.ListView):
    model = Ingredient
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)

        name = self.request.GET.get("name", "")
        context["search_form"] = IngredientSearchForm(
            initial={"name": name}
        )

        return context

    def get_queryset(self):
        name = self.request.GET.get("name")

        if name:
            return super().get_queryset().filter(name__icontains=name)

        return super().get_queryset()


class IngredientCreateView(LoginRequiredMixin, generic.CreateView):
    model = Ingredient
    fields = "__all__"
    success_url = reverse_lazy("kitchen:ingredient-list")


class IngredientUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Ingredient
    fields = "__all__"
    success_url = reverse_lazy("kitchen:ingredient-list")


class IngredientDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Ingredient
    success_url = reverse_lazy("kitchen:ingredient-list")


def remove_add_cook_to_dish(request, pk):
    dish = Dish.objects.get(id=pk)
    cook = Cook.objects.get(id=request.user.id)
    if cook in dish.cooks.all():
        cook.dishes.remove(pk)
    else:
        cook.dishes.add(pk)

    return HttpResponseRedirect(reverse_lazy("kitchen:dish-detail", args=[pk]))

templates/kitchen/cook_confirm_delete.html
{% extends "base-presentation.html" %}
{% block content %}
  <header class="header-2">
    <div class="page-header2 section-height-100 relative" style="background-image: url('{{ ASSETS_ROOT }}/img/curved-images/cook_create2.jpg')">
      <div class="container">
        {% include "includes/search_form.html" %}
        <div class="row">
          <h1 class="text_c_style">Delete this cook?</h1>
          <form action="" method="post">
            {% csrf_token %}
        
            <input type="submit" value="Yes delete" class="table_btn_del">
            <a href="{% url 'kitchen:cook-detail' pk=cook.id %}" class="table_btn_up">
                Cancel
              </a>
          </form>
        </div>
      </div>
      <div class="position-absolute w-100 z-index-1 bottom-0">
        <svg class="waves" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 24 150 40" preserveAspectRatio="none" shape-rendering="auto">
          <defs>
            <path id="gentle-wave" d="M-160 44c30 0 58-18 88-18s 58 18 88 18 58-18 88-18 58 18 88 18 v44h-352z" />
          </defs>
          <g class="moving-waves">
            <use xlink:href="#gentle-wave" x="48" y="-1" fill="rgba(255,255,255,0.40" />
            <use xlink:href="#gentle-wave" x="48" y="3" fill="rgba(255,255,255,0.35)" />
            <use xlink:href="#gentle-wave" x="48" y="5" fill="rgba(255,255,255,0.25)" />
            <use xlink:href="#gentle-wave" x="48" y="8" fill="rgba(255,255,255,0.20)" />
            <use xlink:href="#gentle-wave" x="48" y="13" fill="rgba(255,255,255,0.15)" />
            <use xlink:href="#gentle-wave" x="48" y="16" fill="rgba(255,255,255,0.95" />
          </g>
        </svg>
      </div>
    </div>
  </header>
  {% endblock content %}
  

templates/kitchen/cook_detail.html
{% extends "base-presentation.html" %}

{% block content %}

  <div class="page-header section-height-75 relative" style="background-image: url('{{ ASSETS_ROOT }}/img/curved-images/cook_detail.jpg')">
    <div class="cook_detail">
      <div class="cook-detail-info">
        <div class="blur cook_username shadow-blur">
          <h3 class="">
            Cook name: {{ cook.username }}
          </h3>
        </div>
        <div class="cook_control">
          <a href="{% url 'kitchen:cook-update' pk=cook.id %}" class="table_btn_up">
            Update years of experience
          </a>
          <a href="{% url 'kitchen:cook-delete' pk=cook.id %}" class="table_btn_del">
            Delete
          </a>
        </div>
        <div class="info blur shadow-blur">
            <div class="table_title">
              Short Info
            </div>
            <div class="info-container">
              <div class="info-firstName">
                <p>First Name</p>
              </div>
              <div class="info-value">
                <p>{{ cook.first_name }}</p>
              </div>
            </div>
            <div class="info-container">
              <div class="info-firstName">
                <p>Last Name</p>
              </div>
              <div class="info-value">
                <p>{{ cook.last_name }}</p>
              </div>
            </div>
            <div class="info-container">
              <div class="info-firstName">
                <p>Years of Experience</p>
              </div>
              <div class="info-value">
                <p>{{ cook.years_of_experience }}</p>
              </div>
            </div>
        </div>

      </div>
      <div class="dishes blur shadow-blur">
        <div class="table_title">
          Dishes
        </div>
            <table class="table ">
              <tr>
                <th class="cook_teble-head">Dish Name</th>
                <th class="cook_teble-head">Dish Type</th>
              </tr>
              {% for dish in cook.dishes.all %}
              <tr>
                <td class="cook_teble-content">{{ dish.name }}</a></td>
                <td class="cook_teble-content">{{ dish.dish_type.name }}</td>
              </tr>
              {% endfor %}
            </table>
    </div>
    </div>
  </div>


{% endblock %}

templates/kitchen/cook_list.html
{% extends "base-presentation.html" %}

{% block search %}

{% endblock search %}
  
{% block content %}
<div class="intro" style="background-image: url('{{ ASSETS_ROOT }}/img/curved-images/cook_list3.jpg')">
  <div>
    {% include "includes/search_form.html" %}
  </div>
  <div class="table_wrapper">
    <div class="table_container blur shadow-blur">
      <table class="table ">
        <tr>
          <th class="cook_teble-head">Username</th>
          <th class="cook_teble-head">First name</th>
          <th class="cook_teble-head">Last name</th>
          <th class="cook_teble-head">Years of Experience</th>
        </tr>
        {% for cook in cook_list %}
        <tr>
          <td class="cook_teble-content"><a href="{% url 'kitchen:cook-detail' pk=cook.id %} ">{{ cook.username }} {% if user == cook %} -> (Me){% endif %}</a></td>
          <td class="cook_teble-content">{{ cook.first_name }}</td>
          <td class="cook_teble-content">{{ cook.last_name }}</td>
          <td class="cook_teble-content">{{ cook.years_of_experience }}</td>
        </tr>
        {% endfor %}
      </table>
    </div>
    <div class="control">
      <a href="{% url 'kitchen:cook-create' %}" class=" table_btn ">
        Create
      </a>
      <div>
        {% include "includes/pagination.html" %}
      </div>
    </div>
  </div>


</div>
{% endblock content %}

templates/kitchen/dish_detail.html
{% extends "base-presentation.html" %}

{% block content %}
  <div class="page-header section-height-75 relative" style="background-image: url('{{ ASSETS_ROOT }}/img/curved-images/dish_detail.png')">
    <div class="dish_detail">
      <div class="dish-detail-info">
        <div class="info_header">
          <p class="info_header-text blur shadow-blur">{{ dish.name }}</p>
          <p class="info_header-text blur shadow-blur">{{ dish.price }} $</p>
        </div>
        <div class="info_desc blur shadow-blur">
          {{ dish.description }}
        </div>
        <div class="info_type blur shadow-blur">
          {{ dish.dish_type }}
        </div>
          <div class="dish_btn">
            <a href="{% url 'kitchen:dish-list' %}" class=" table_btn ">
              Back to list
            </a>
            {% if user in dish.cooks.all %}
              <a href="{% url 'kitchen:remove-add-cook-to-dish' pk=dish.id %}" class="table_btn_del">Delete me from this dish</a>
            {% else %}
              <a href="{% url 'kitchen:remove-add-cook-to-dish' pk=dish.id %}" class="table_btn_up">Assign me to this dish</a> 
            {% endif %}
          </div>
      </div>
      <div class="dish_container">
        <div class="dish_type blur shadow-blur">
          <div class="table_title">
            <h4>Cooks</h4>
          </div>
          <div class="dish_type-data">
            {% for cook in dish.cooks.all %}
              <p>{{ cook.first_name }} {{ cook.last_name }} {% if user == cook %} -> (Me){% endif %}</p>
            {% endfor %}
          </div>
        </div>
        <div class="dish_type blur shadow-blur">
          <div class="table_title">
            <h4>Ingredients</h4>
          </div>
          <div class="dish_type-data">
            {% for ingredient in dish.ingredients.all %}
              <p>{{ ingredient.name }} -> {{ ingredient.amount }} ({{ ingredient.unit }}) </p>
            {% endfor %}
          </div>
        </div>
      </div> 
    </div>  
  </div>
  

{% endblock %}
    

templates/kitchen/dish_form.html
{% extends "base-presentation.html" %}
{% load crispy_forms_filters %}

{% block content %}
<form action="" method="post" novalidate>
  {% csrf_token %}
  <div class="page-header section-height-75 relative" style="background-image: url('{{ ASSETS_ROOT }}/img/curved-images/cook_list.avif')">
    <div class="dish_detail">
      <div class="dish-detail-info">
        <div class="info_header">
          <p>{{ form.name }}</p>
          <p>{{ form.price }}</p>
        </div>
        <div class="">
          {{ form.description }}
        </div>
        <div class="info_header">
          <p>{{ form.dish_type }}</p>
        </div>
        <div class="dish_detail">
          <input type="submit" value="Submit" class="table_btn">
        </div>
      </div>
      <div class="dish_container">
        <div class="dish_type blur shadow-blur">
          <div class="table_title">
            <h4>Cooks</h4>
          </div>
          <div class="dish_type-data">
            {{ form.cooks }}
          </div>
        </div>
        <div class="dish_type blur shadow-blur">
          <div class="table_title">
            <h4>Ingredients</h4>
          </div>
          <div class="dish_type-data">
            {{ form.ingredients }}
          </div>
        </div>
      </div>
      

    </div>
  </div>
</form>
{% if form.errors %}
        <div class="alert-danger">
          <p> Fields -> name, price, dish-type, cooks and ingredients cannot be empty </p>
        </div>
      {% endif %}

{% endblock %}

templates/kitchen/dishtype_list.html
{% extends "base-presentation.html" %}
{% block content %}
<div class="intro" style="background-image: url('{{ ASSETS_ROOT }}/img/curved-images/type_list2.jpg')">
  <div>
    {% include "includes/search_form.html" %}
  </div>
  <div class="table_wrapper">
    <div class="table_container blur shadow-blur">
      <table class="table ">
        <tr>
          <th class="cook_teble-head">ID</th>
          <th class="cook_teble-head">TYPE NAME</th>
          <th class="cook_teble-head">DELETE</th>
          <th class="cook_teble-head">UPDATE</th>
        </tr>
        {% for dish_type in dishtype_list %}
        <tr>
          <td class="cook_teble-content">{{ dish_type.id }}
          <td class="cook_teble-content">{{ dish_type.name }}
          <td class="cook_teble-content"><a href="{% url 'kitchen:dishtype-delete' pk=dish_type.id %}">
            Delete
          </a></td>
          <td class="cook_teble-content"><a href="{% url 'kitchen:dishtype-update' pk=dish_type.id %}">
            Update
          </a></td>
        </tr>
        {% endfor %}
      </table>
    </div>
    <div class="control">
      <a href="{% url 'kitchen:dishtype-create' %}" class=" table_btn ">
        Create
      </a>
      <div>
        {% include "includes/pagination.html" %}
      </div>
    </div>
  </div>


</div>
{% endblock content %}

templates/kitchen/ingredient_list.html
{% extends "base-presentation.html" %}
{% block content %}
<div class="intro" style="background-image: url('{{ ASSETS_ROOT }}/img/curved-images/ingred.jpg')">
  <div>
    {% include "includes/search_form.html" %}
  </div>
  <div class="table_wrapper">
    <div class="table_container blur shadow-blur">
      <table class="table ">
        <tr>
          <th class="cook_teble-head">NAME</th>
          <th class="cook_teble-head">ANOUNT</th>
          <th class="cook_teble-head">UNIT</th>
          <th class="cook_teble-head">DELETE</th>
          <th class="cook_teble-head">UPDATE</th>
        </tr>
        {% for ingredient in ingredient_list %}
        <tr>
          <td class="cook_teble-content">{{ ingredient.name }}
          <td class="cook_teble-content">{{ ingredient.amount }}
            <td class="cook_teble-content">{{ ingredient.unit }}
          <td class="cook_teble-content"><a href="{% url 'kitchen:ingredient-delete' pk=ingredient.id %}">
            Delete
          </a></td>
          <td class="cook_teble-content"><a href="{% url 'kitchen:ingredient-update' pk=ingredient.id %}">
            Update
          </a></td>
        </tr>
        {% endfor %}
      </table>
    </div>
    <div class="control">
      <a href="{% url 'kitchen:ingredient-create' %}" class=" table_btn ">
        Create
      </a>
      <div>
        {% include "includes/pagination.html" %}
      </div>
    </div>
  </div>


</div>
{% endblock content %}

templates/kitchen/no_page.html
{% extends "login-presentation.html" %}
{% block content %}
<header class="header-2">
    <div class="page-header2 section-height-100 relative"
        style="background-image: url('{{ ASSETS_ROOT }}/img/curved-images/cook_create2.jpg')">
        <div class="container">
            <div class="row">
                <h1 class="text_c_style">It`s not real project, of course we don`t have link for it.</h1>

                <a class="table_btn_up" href="{% url 'kitchen:index'%}">Go to home page</a>
            </div>
        </div>
        <div class="position-absolute w-100 z-index-1 bottom-0">
            <svg class="waves" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
                viewBox="0 24 150 40" preserveAspectRatio="none" shape-rendering="auto">
                <defs>
                    <path id="gentle-wave"
                        d="M-160 44c30 0 58-18 88-18s 58 18 88 18 58-18 88-18 58 18 88 18 v44h-352z" />
                </defs>
                <g class="moving-waves">
                    <use xlink:href="#gentle-wave" x="48" y="-1" fill="rgba(255,255,255,0.40" />
                    <use xlink:href="#gentle-wave" x="48" y="3" fill="rgba(255,255,255,0.35)" />
                    <use xlink:href="#gentle-wave" x="48" y="5" fill="rgba(255,255,255,0.25)" />
                    <use xlink:href="#gentle-wave" x="48" y="8" fill="rgba(255,255,255,0.20)" />
                    <use xlink:href="#gentle-wave" x="48" y="13" fill="rgba(255,255,255,0.15)" />
                    <use xlink:href="#gentle-wave" x="48" y="16" fill="rgba(255,255,255,0.95" />
                </g>
            </svg>
        </div>
    </div>
</header>
{% endblock content %}